---
#####################################################################################################################
# Configurations for Splunk inputs.conf
#####################################################################################################################

#####################################################################################################################
# [SSL]
#####################################################################################################################

# serverCert

- name: Set serverCert
  ini_file: dest="{{ splunk_conf_path }}/inputs.conf"
            section=SSL 
            option=serverCert
            value={{ splunk_inputs_conf.SSL.serverCert }}
            state=present
  when: splunk_inputs_conf.SSL.serverCert is defined
  tags: 
    - inputs_SSL_serverCert

- name: Unset serverCert (default)
  ini_file: dest="{{ splunk_conf_path }}/inputs.conf"
            section=SSL 
            option=serverCert
            state=absent
  when: splunk_inputs_conf.SSL.serverCert is undefined
  tags:
    - inputs_SSL_serverCert

