---
#####################################################################################################################
# Configurations for Splunk outputs.conf
#####################################################################################################################

#####################################################################################################################
# [tcpout:<tcpout:target_group>]
#####################################################################################################################

# tcpout:target_group indexerDiscovery

- name: "Set tcpout:target_group indexerDiscovery"
  ini_file: dest={{ splunk_conf_path }}/outputs.conf
            section=tcpout:{{ item.key }}
            option=indexerDiscovery
            value={{ item.value.indexerDiscovery }}
            state=present
  with_dict: "{{ splunk_outputs_conf.tcpout.target_group }}"
  when: splunk_outputs_conf.tcpout.target_group.{{ item.key }}.indexerDiscovery is defined

- name: "Unset tcpout:target_group indexerDiscovery (default)"
  ini_file: dest={{ splunk_conf_path }}/outputs.conf
            section=tcpout:{{ item.key }}
            option=indexerDiscovery
            state=absent
  with_dict: "{{ splunk_outputs_conf.tcpout.target_group }}"
  when: splunk_outputs_conf.tcpout.target_group.{{ item.key }}.indexerDiscovery is undefined

