---
#####################################################################################################################
# Configurations for Splunk outputs.conf
#####################################################################################################################

#####################################################################################################################
# [tcpout:<tcpout:target_group>]
#####################################################################################################################

# tcpout:target_group server

- name: "Set tcpout:target_group server"
  ini_file: dest={{ splunk_conf_path }}/outputs.conf
            section=tcpout:{{ item.key }}
            option=server
            value={{ item.value.server | join(",") }}
            state=present
  with_dict: "{{ splunk_outputs_conf.tcpout.target_group }}"
  when: splunk_outputs_conf.tcpout.target_group.{{ item.key }}.server is defined
 
- name: "Unset tcpout:target_group server (default)"
  ini_file: dest={{ splunk_conf_path }}/outputs.conf
            section=tcpout:{{ item.key }}
            option=server
            state=absent
  with_dict: "{{ splunk_outputs_conf.tcpout.target_group }}"
  when: splunk_outputs_conf.tcpout.target_group.{{ item.key }}.server is undefined

