---
#####################################################################################################################
# Configurations for Splunk outputs.conf
#####################################################################################################################

#####################################################################################################################
# [tcpout:<tcpout:target_group>]
#####################################################################################################################

# tcpout:target_group sslVerifyServerCert

- name: "Set tcpout:target_group sslVerifyServerCert"
  ini_file: dest={{ splunk_conf_path }}/outputs.conf
            section=tcpout:{{ item.key }}
            option=sslVerifyServerCert
            value={{ item.value.sslVerifyServerCert }}
            state=present
  with_dict: "{{ splunk_outputs_conf.tcpout.target_group }}"
  when: splunk_outputs_conf.tcpout.target_group.{{ item.key }}.sslVerifyServerCert is defined and
        splunk_outputs_conf.tcpout.target_group.{{ item.key }}.sslVerifyServerCert == true
  tags:
    - output_tcpout.target_group_sslVerifyServerCert

- name: "Unset tcpout:target_group sslVerifyServerCert (default)"
  ini_file: dest={{ splunk_conf_path }}/outputs.conf
            section=tcpout:{{ item.key }}
            option=sslVerifyServerCert
            state=absent
  with_dict: "{{ splunk_outputs_conf.tcpout.target_group }}"
  when: splunk_outputs_conf.tcpout.target_group.{{ item.key }}.sslVerifyServerCert is undefined or
        splunk_outputs_conf.tcpout.target_group.{{ item.key }}.sslVerifyServerCert != true
  tags: 
    - output_tcpout.target_group_sslVerifyServerCert
