---
#####################################################################################################################
# Configurations for Splunk outputs.conf
#####################################################################################################################

#####################################################################################################################
# [tcpout:<tcpout:target_group>]
#####################################################################################################################

# tcpout:target_group useAck

- name: "Set tcpout:target_group useACK"
  ini_file: dest={{ splunk_conf_path }}/outputs.conf
            section=tcpout:{{ item.key }}
            option=useACK
            value={{ item.value.useACK }}
            state=present
  with_dict: "{{ splunk_outputs_conf.tcpout.target_group }}"
  when: splunk_outputs_conf.tcpout.target_group.{{ item.key }}.useACK is defined and
        splunk_outputs_conf.tcpout.target_group.{{ item.key }}.useACK == true
  tags: 
  - output_tcpout.target_group_useAck

- name: "Unset tcpout:target_group useACK (default)"
  ini_file: dest={{ splunk_conf_path }}/outputs.conf
            section=tcpout:{{ item.key }}
            option=useACK
            state=absent
  with_dict: "{{ splunk_outputs_conf.tcpout.target_group }}"
  when: splunk_outputs_conf.tcpout.target_group.{{ item.key }}.useACK is undefined
  tags: 
  - output_tcpout.target_group_useAck

