---
#####################################################################################################################
# Configurations for Splunk inputs.conf
#####################################################################################################################

#####################################################################################################################
# [splunktcp-ssl:<port>]
#####################################################################################################################

- name: Set splunktcp-ssl
  ini_file: dest="{{ splunk_conf_path }}/inputs.conf"
            section=splunktcp-ssl:{{ splunk_inputs_conf.splunktcp_ssl.port }}  
            state=present
  when: splunk_inputs_conf.splunktcp_ssl.port is defined

- name: Unset splunktcp-ssl (default)
  replace: dest="{{ splunk_conf_path }}/inputs.conf"
           regexp='\[splunktcp-ssl:\d+\]\n'
           replace=''
  when: splunk_inputs_conf.splunktcp_ssl.port is undefined
