---
#####################################################################################################################
# Configurations for Splunk inputs.conf
#####################################################################################################################

#####################################################################################################################
# [SSL]
#####################################################################################################################

# rootCA

- name: Set rootCA
  ini_file: dest="{{ splunk_conf_path }}/inputs.conf"
            section=SSL
            option=rootCA 
            value={{ splunk_inputs_conf.SSL.rootCA }}
            state=present
  when: splunk_inputs_conf.SSL.rootCA is defined
  tags: inputs_SSL_rootCA

- name: Unset rootCA (default)
  ini_file: dest="{{ splunk_conf_path }}/inputs.conf"
            section=SSL 
            option=rootCA
            state=absent
  when: splunk_inputs_conf.SSL.rootCA is undefined
  tags: inputs_SSL_rootCA

# serverCert

- name: Set serverCert
  ini_file: dest="{{ splunk_conf_path }}/inputs.conf"
            section=SSL 
            option=serverCert
            value={{ splunk_inputs_conf.SSL.serverCert }}
            state=present
  when: splunk_inputs_conf.SSL.serverCert is defined
  tags: inputs_SSL_serverCert

- name: Unset serverCert (default)
  ini_file: dest="{{ splunk_conf_path }}/inputs.conf"
            section=SSL 
            option=serverCert
            state=absent
  when: splunk_inputs_conf.SSL.serverCert is undefined
  tags: inputs_SSL_serverCert

# password

- name: Set password
  ini_file: dest="{{ splunk_conf_path }}/inputs.conf"
            section=SSL
            option=password
            value={{ splunk_inputs_conf.SSL.password }}
            state=present
  when: splunk_inputs_conf.SSL.password is defined
  tags: inputs_SSL_password

- name: Unset password (default)
  ini_file: dest="{{ splunk_conf_path }}/inputs.conf"
            section=SSL
            option=password
            state=absent
  when: splunk_inputs_conf.SSL.password is undefined
  tags: inputs_SSL_password

