---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [general]
#####################################################################################################################

# site

- name: Set site (dynamic)
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=general
            option=site
            value={{ hostvars[inventory_hostname].splunk_site }}
            state=present
  when: splunk_server_conf.general.site is defined and
        splunk_server_conf.general.site == "dynamic"

- name: Set site (static)
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=general
            option=site
            value={{ splunk_server_conf.general.site }}
            state=present
  when: splunk_server_conf.general.site is defined and
        splunk_server_conf.general.site != "dynamic"

- name: Unset site (default)
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=general
            option=site
            state=absent
  when: splunk_server_conf.general.site is undefined

