---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [sslConfig]
#####################################################################################################################

# sslKeysfilePassword

- name: Set sslKeysfilePassword
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=sslConfig
            option=sslKeysfilePassword
            value={{ splunk_server_conf.sslConfig.sslKeysfilePassword }}
            state=present
  when: splunk_server_conf.sslConfig.sslKeysfilePassword is defined
  tags: server_conf_sslconfig_sslkeysfilepassword

- name: Unset sslKeysfilePassword
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=sslConfig
            option=sslKeysfilePassword
            state=absent
  when: splunk_server_conf.sslConfig.sslKeysfilePassword is undefined
  tags: server_conf_sslconfig_sslkeysfilepassword

