---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [clustering]
#####################################################################################################################

# cluster_label

- name: Set cluster_label
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=cluster_label
            value="{{ splunk_cluster_label }}"
            state=present
  when: splunk_cluster_label is defined

- name: Unset cluster_label (default)
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=cluster_label
            state=absent
  when: splunk_cluster_label is undefined
