---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [clustering]
#####################################################################################################################

# master_uri

- name: Set master_uri (dynamic)
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=master_uri
            value="https://{{ groups['masternode'][0] }}:8089"
            state=present
  when: splunk_server_conf.clustering.master_uri is defined and
        splunk_server_conf.clustering.master_uri == "dynamic"
  tags: server_clustering_master_uri

- name: Set master_uri (static)
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=master_uri
            value={{ splunk_server_conf.clustering.master_uri }}
            state=present
  when: splunk_server_conf.clustering.master_uri is defined and
        splunk_server_conf.clustering.master_uri != "dynamic"
  tags: server_clustering_master_uri

- name: Unset master_uri (default)
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=master_uri
            state=absent
  when: splunk_server_conf.clustering.master_uri is undefined
  tags: server_clustering_master_uri

