---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [clustering]
#####################################################################################################################

#  multisite

- name: Set multisite 
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=multisite
            value={{ splunk_server_conf.clustering.multisite }}
            state=present
  when: splunk_server_conf.clustering.multisite is defined or
        splunk_server_conf.clustering.multisite == true

- name: Unset multisite (default)
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=mode
            state=absent
  when: splunk_server_conf.clustering.multisite is undefined or
        splunk_server_conf.clustering.multisite != true

