---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [clustering]
#####################################################################################################################

# replication_factor

- name: Set replication_factor
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=replication_factor
            value={{ splunk_server_conf.clustering.replication_factor }}
            state=present
  when: splunk_server_conf.clustering.replication_factor is defined or
        splunk_server_conf.clustering.replication_factor != 3

- name: Unset replication_factor (default)
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=replication_factor
            state=absent
  when: splunk_server_conf.clustering.replication_factor is undefined or
        splunk_server_conf.clustering.replication_factor == 3

