---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [clustering]
#####################################################################################################################

# search_factor

- name: Set search_factor
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=search_factor
            value={{ splunk_server_conf.clustering.search_factor }}
            state=present
  when: splunk_server_conf.clustering.search_factor is defined
  tags: 
    - server_clustering_search_factor

- name: Unset search_factor (default)
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=search_factor
            state=absent
  when: splunk_server_conf.clustering.search_factor is undefined or
        splunk_server_conf.clustering.search_factor == 2
  tags: 
    - server_clustering_search_factor

