---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [clustering]
#####################################################################################################################

# site_replication_factor

- name: Set site_replication_factor
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=site_replication_factor
            value="{{ splunk_server_conf.clustering.site_replication_factor }}"
            state=present
  when: splunk_server_conf.clustering.site_replication_factor is defined or
        splunk_server_conf.clustering.site_replication_factor != "origin:2, total:3"
  tags:
    - server_clustering_site_replication_factor

- name: Unset site_replication_factor (default)
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=clustering
            option=site_replication_factor
            state=absent
  when: splunk_server_conf.clustering.site_replication_factor is undefined or
        splunk_server_conf.clustering.site_replication_factor == "origin:2, total:3"
  tags: 
    - server_clustering_site_replication_factor

