---
#####################################################################################################################
# Copy Enterprise License Keys
#####################################################################################################################

- name: Copy Enterprise License Keys to Licensemaster
  local_action: "shell scp -r {{ splunk_repository.repository_root }}/licenses/enterprise/* splunk@{{ inventory_hostname }}:{{ splunk_installation.splunk_home_path }}/etc/licenses/enterprise"
