---

- name: First time start Splunk
  service: name=splunk state=started

- name: Apply IA-searchhead app
  git: repo=https://github.com/my2ndhead/IA-searchhead.git dest=/opt/splunk/etc/apps/IA-searchhead version=master force=yes

- name: Set enableSplunkWebSSL
  ini_file: dest=/opt/splunk/etc/apps/IA-searchhead/default/web.conf section=settings option=enableSplunkWebSSL value={{ splunk_web_enableSplunkWebSSL }}

- name: Set httpport
  ini_file: dest=/opt/splunk/etc/apps/IA-searchhead/default/web.conf section=settings option=httpport value={{ splunk_web_httpport }}
  when: splunk_web_httpport != "8000"


