---

- name: Install Splunk
  yum: name="/tmp/{{ splunk_release_file }}" state=present

- name: Create common splunk.secret
  template: src=etc/auth/splunk.secret.j2 dest=/opt/splunk/etc/auth/splunk.secret

- name: Set permissions for splunk.secret
  file: path=/opt/splunk/etc/auth/splunk.secret mode=0400 owner=splunk group=splunk

- name: Start during boot
  command: /opt/splunk/bin/splunk enable boot-start -user splunk --answer-yes --accept-license
