---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [replication_port-ssl:<port>]
#####################################################################################################################

- name: Set replication_port-ssl
  ini_file: dest="{{ splunk_conf_path }}/server.conf"
            section="replication_port-ssl://{{ splunk_server_conf.replication_port_ssl.port }}"
            state=present
  when: splunk_server_conf.replication_port_ssl.port is defined

- name: Check actual config for replication_port-ssl
  shell: grep 'replication_port-ssl:' {{ splunk_conf_path }}/server.conf | sed 's/\[replication_port-ssl:\/\/\(.*\)]/\1/'
  register: splunk_server_replication_port_ssl_port_inifile

- name: Unset replication_port-ssl (default)
  ini_file: dest="{{ splunk_conf_path }}/server.conf"
            section="replication_port-ssl://{{ splunk_server_replication_port_ssl_port_inifile.stdout }}"
            state=absent
  when: splunk_server_conf.replication_port_ssl.port is undefined and
        splunk_server_replication_port_ssl_port_inifile.stdout != ""
