---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [shclustering]
#####################################################################################################################

# election

- name: Set shclustering election
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=shclustering
            option=election
            value={{ splunk_server_conf.shclustering.election }}
            state=present
  when: splunk_server_conf.shclustering.election is defined
  tags:
    - server_shclustering_election

- name: Unset shclustering election
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=shclustering
            option=election
            state=absent
  when: splunk_server_conf.shclustering.election is undefined
  tags:
    - server_shclustering_election
