---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [shclustering]
#####################################################################################################################

# replication_factor

- name: Set shclusetering replication_factor
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=shclustering
            option=replication_factor
            value={{ splunk_server_conf.shclustering.replication_factor }}
            state=present
  when: splunk_server_conf.shclustering.replication_factor is defined or
        splunk_server_conf.shclustering.replication_factor != 3

- name: Unset shclustering replication_factor (default)
  ini_file: dest={{ splunk_conf_path }}/server.conf
            section=shclustering
            option=replication_factor
            state=absent
  when: splunk_server_conf.shclustering.replication_factor is undefined or
        splunk_server_conf.shclustering.replication_factor == 3

