---

- name: Configure app files
  copy: src="{{ item }}"
        dest="{{ splunk_installation.splunk_home_path }}/etc/apps/Splunk_TA_windows/local/"
  when: splunk_apps.Splunk_TA_windows is defined and
        inventory_hostname in groups['heavyforwarder']
  with_fileglob:
    - etc/apps/Splunk_TA_windows/local/*.conf
    

- name: Configure deployment-app files
  copy: src="{{ item }}"
        dest="{{ splunk_installation.splunk_home_path }}/etc/deployment-apps/Splunk_TA_windows/local/"
  when: splunk_apps.Splunk_TA_windows is defined and
        inventory_hostname in groups['deploymentserver']
  with_fileglob:
    - etc/deployment-apps/Splunk_TA_windows/local/*.conf


- name: Configure shcluster/apps files
  copy: src="{{ item }}"
        dest="{{ splunk_installation.splunk_home_path }}/etc/shcluster/apps/Splunk_TA_windows/local/"
  when: splunk_apps.Splunk_TA_windows is defined and
        inventory_hostname in groups['deployer']
  with_fileglob:
    - etc/shcluster/apps/Splunk_TA_windows/local/*.conf

- name: Configure master-apps files
  copy: src="{{ item }}"
        dest="{{ splunk_installation.splunk_home_path }}/etc/master-apps/Splunk_TA_windows/local/"
  when: splunk_apps.Splunk_TA_windows is defined and
        inventory_hostname in groups['clustermaster']
  with_fileglob:
    - etc/master-apps/Splunk_TA_windows/local/*.conf
