---
#####################################################################################################################
# Configurations for Splunk web.conf
#####################################################################################################################

#####################################################################################################################
# [settings]
#####################################################################################################################

# enableSplunkWebSSL

- name: Set enableSplunkWebSSL
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings option=enableSplunkWebSSL 
            value={{ splunk_web_conf.settings.enableSplunkWebSSL }}
            state=present
  when: splunk_web_conf.settings.enableSplunkWebSSL is defined and
        splunk_web_conf.settings.enableSplunkWebSSL == true

- name: Unset enableSplunkWebSSL (default)
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=enableSplunkWebSSL
            state=absent
  when:  splunk_web_conf.settings.enableSplunkWebSSL is undefined or 
         splunk_web_conf.settings.enableSplunkWebSSL == false
