---
#####################################################################################################################
# Configurations for Splunk web.conf
#####################################################################################################################

#####################################################################################################################
# [settings]
#####################################################################################################################

# enableSplunkWebSSL

- name: Set enableSplunkWebSSL
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings option=enableSplunkWebSSL 
            value={{ splunk_web_conf.settings_enableSplunkWebSSL }}
            state=present
  when: splunk_web_conf.settings_enableSplunkWebSSL is defined and
        splunk_web_conf.settings_enableSplunkWebSSL != 1

- name: Unset enableSplunkWebSSL (default)
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=enableSplunkWebSSL
            state=absent
  when:  splunk_web_conf.settings_enableSplunkWebSSL is defined and
         splunk_web_conf.settings_enableSplunkWebSSL == 1

# httpport

- name: Set httpport
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=httpport
            value={{ splunk_web_conf.settings_httpport }}
            state=present
  when: splunk_web_conf.settings_httpport is defined and 
        splunk_web_conf.settings_httpport != 8000

- name: Unset httpport (default)
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=httpport
            state=absent

# startwebserver

- name: Set startwebserver
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=startwebserver
            value={{ splunk_web_conf.settings_startwebserver }}
  when: splunk_web_conf.settings_startwebserver is defined and
        splunk_web_conf.settings_startwebserver == 0

- name: Unset startwebserver (default)
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=startwebserver
            state=absent
  when: splunk_web_conf.settings_startwebserver is defined and
        splunk_web_conf.settings_startwebserver == 1

# privKeyPath

- name: Set privkeyPath
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=privKeyPath
            value={{ splunk_web_conf.settings_privKeyPath }}
            state=present
  when: splunk_web_conf.settings_privKeyPath is defined and
        splunk_web_conf.settings_privKeyPath != "etc/auth/splunkweb/privkey.pem"

- name: Unset privkeyPath (default)
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=privKeyPath
            state=absent
  when: splunk_web_conf.settings_privKeyPath is defined and 
        splunk_web_conf.settings_privKeyPath == "etc/auth/splunkweb/privkey.pem"

# cacertPath

- name: Set CaCert path
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=caCertPath
            value={{ splunk_web_conf.settings_caCertPath }}
            state=present
  when: splunk_web_conf.settings_caCertPath is defined and
        splunk_web_conf.settings_caCertPath != "etc/auth/splunkweb/cert.pem"

- name: Unset CaCert path (default)
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=caCertPath
            state=absent
  when: splunk_web_conf.settings_caCertPath is defined and 
        splunk_web_conf.settings_caCertPath == "etc/auth/splunkweb/cert.pem"

# updateChecker

- name: Set updateChecker
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=updateCheckerBaseURL
            value={{ splunk_web_conf.settings_updateCheckerBaseURL }}
            state=present
  when: splunk_web_conf.settings_updateCheckerBaseURL is defined and 
        splunk_web_conf.settings_updateCheckerBaseURL != "http://quickdraw.Splunk.com/js/"

- name: Unset updateChecker (default)
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=updateCheckerBaseURL
            state=absent
  when: splunk_web_conf.settings_updateCheckerBaseURL == "http://quickdraw.Splunk.com/js/" 
