---
#####################################################################################################################
# Configurations for Splunk web.conf
#####################################################################################################################

#####################################################################################################################
# [settings]
#####################################################################################################################

# enableSplunkWebSSL

- name: Set enableSplunkWebSSL
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings option=enableSplunkWebSSL 
            value={{ splunk_web_conf.settings.enableSplunkWebSSL }}
            state=present
  when: splunk_web_conf.settings.enableSplunkWebSSL is defined and
        splunk_web_conf.settings.enableSplunkWebSSL != 1

- name: Unset enableSplunkWebSSL (default)
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=enableSplunkWebSSL
            state=absent
  when:  splunk_web_conf.settings.enableSplunkWebSSL is undefined or 
         splunk_web_conf.settings.enableSplunkWebSSL == 1

# httpport

- name: Set httpport
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=httpport
            value={{ splunk_web_conf.settings.httpport }}
            state=present
  when: splunk_web_conf.settings.httpport is defined and 
        splunk_web_conf.settings.httpport != 8000

- name: Unset httpport (default)
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=httpport
            state=absent
  when: splunk_web_conf.settings.httpport is undefined or
        splunk_web_conf.settings.httpport == "8000"

# startwebserver

- name: Set startwebserver
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=startwebserver
            value={{ splunk_web_conf.settings.startwebserver }}
  when: splunk_web_conf.settings.startwebserver is defined and
        splunk_web_conf.settings.startwebserver == 0

- name: Unset startwebserver (default)
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=startwebserver
            state=absent
  when: splunk_web_conf.settings.startwebserver is undefined or
        splunk_web_conf.settings.startwebserver == 1

# privKeyPath

- name: Set privkeyPath
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=privKeyPath
            value={{ splunk_web_conf.settings.privKeyPath }}
            state=present
  when: splunk_web_conf.settings.privKeyPath is defined and
        splunk_web_conf.settings.privKeyPath != "etc/auth/splunkweb/privkey.pem"

- name: Unset privkeyPath (default)
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=privKeyPath
            state=absent
  when: splunk_web_conf.settings.privKeyPath is undefined or 
        splunk_web_conf.settings.privKeyPath == "etc/auth/splunkweb/privkey.pem"

# cacertPath

- name: Set CaCert path
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=caCertPath
            value={{ splunk_web_conf.settings.caCertPath }}
            state=present
  when: splunk_web_conf.settings.caCertPath is defined and
        splunk_web_conf.settings.caCertPath != "etc/auth/splunkweb/cert.pem"

- name: Unset CaCert path (default)
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=caCertPath
            state=absent
  when: splunk_web_conf.settings.caCertPath is undefined or
        splunk_web_conf.settings.caCertPath == "etc/auth/splunkweb/cert.pem"

# updateChecker

- name: Set updateChecker
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=updateCheckerBaseURL
            value={{ splunk_web_conf.settings.updateCheckerBaseURL }}
            state=present
  when: splunk_web_conf.settings.updateCheckerBaseURL is defined and 
        splunk_web_conf.settings.updateCheckerBaseURL != "http://quickdraw.Splunk.com/js/"

- name: Unset updateChecker (default)
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=updateCheckerBaseURL
            state=absent
  when: splunk_web_conf.settings.updateCheckerBaseURL is undefined or 
        splunk_web_conf.settings.updateCheckerBaseURL == "http://quickdraw.Splunk.com/js/"
